version: "3"

services:
  partner_delivery:
    container_name: partner_delivery
    entrypoint: sh run.sh
    tty: true
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://tom:tom123@service.postgres:5432/partner_delivery
    stdin_open: true
    image: container_partner_delivery:latest
    build:
      context: .
    volumes:
      - ./:/opt/app/partner_delivery/
    ports:
      - "5000:5000"


  service.postgres:
    container_name: partner_delivery_postgres
    image: postgis/postgis
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=tom
      - POSTGRES_PASSWORD=tom123
      - POSTGRES_DB=partner_delivery

volumes:
  postgres: